# -*- coding: utf-8 -*-
"""Выявление_спама_в смс-сообщениях_методами_текстового_анализа.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHluv5TuhTmhW4cXZ_xBkELJTtbp57Bl
"""

!pip install pandas scikit-learn nltk

!pip install torch

#!pip uninstall torch torchvision torchaudio -y

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from collections import Counter
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import precision_recall_fscore_support

from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification, get_scheduler
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.optim import AdamW
from tqdm.auto import tqdm

from sklearn.metrics import confusion_matrix

df = pd.read_csv('/content/VKR_dataset-F.csv')
df.head()

df.shape

df = df[['LABEL', 'TEXT']]

df = df.dropna()

df.shape

df['LABEL'] = df['LABEL'].str.lower()

df['LABEL'].value_counts()

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)

    words = text.split()
    words = [w for w in words if w not in stop_words]

    return ' '.join(words)

df['clean_text'] = df['TEXT'].apply(clean_text)

df

le = LabelEncoder()
df['LABEL_ENC'] = le.fit_transform(df['LABEL'])

df['LABEL_ENC'].value_counts()

plt.figure()
df['LABEL'].value_counts().plot(kind='bar')
plt.title("Распределение классов")
plt.xlabel("Класс")
plt.ylabel("Количество")
plt.show()

class_counts = df['LABEL'].value_counts()
class_percent = df['LABEL'].value_counts(normalize=True) * 100
print("\nПроцентное соотношение классов:\n", class_percent)

df['text_length'] = df['clean_text'].apply(lambda x: len(x.split()))

plt.figure(figsize=(10,5))
for label in df['LABEL'].unique():
    subset = df[df['LABEL'] == label]
    plt.hist(subset['text_length'], bins=30, alpha=0.6, label=label)

plt.title("Распределение длины текста по классам")
plt.xlabel("Количество слов")
plt.ylabel("Количество сообщений")
plt.legend()
plt.show()

df['text_length'] = df['clean_text'].apply(lambda x: len(x.split()))

mean_length_all = df['text_length'].mean()
median_length_all = df['text_length'].median()
max_length_all = df['text_length'].max()
min_length_all = df['text_length'].min()

print(f"Средняя длина текста: {mean_length_all:.2f} слов")
print(f"Медианная длина текста: {median_length_all} слов")
print(f"Минимальная длина текста: {min_length_all} слов")
print(f"Максимальная длина текста: {max_length_all} слов")

print("\nСредняя длина текста по классам:")
print(df.groupby('LABEL')['text_length'].mean())

from collections import Counter
import seaborn as sns

top_n = 15

for label in df['LABEL'].unique():
    words = ' '.join(df[df['LABEL'] == label]['clean_text']).split()
    word_counts = Counter(words)
    common_words = word_counts.most_common(top_n)

    words, counts = zip(*common_words)

    plt.figure(figsize=(10,5))
    sns.barplot(x=list(counts), y=list(words), palette="viridis")
    plt.title(f"Топ-{top_n} слов для класса '{label}'")
    plt.xlabel("Количество")
    plt.ylabel("Слова")
    plt.show()

train_idx, test_idx = train_test_split(df.index,test_size=0.2,random_state=42,stratify=df['LABEL_ENC'])
train_df = df.loc[train_idx].reset_index(drop=True)
test_df = df.loc[test_idx].reset_index(drop=True)

vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1,2))

X_train = vectorizer.fit_transform(train_df['clean_text'])
X_test = vectorizer.transform(test_df['clean_text'])

y_train = train_df['LABEL_ENC']
y_test = test_df['LABEL_ENC']

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

accuracy_score(y_test, y_pred_lr)

print(classification_report(y_test, y_pred_lr))

cm = confusion_matrix(y_test, y_pred_lr)
labels = le.classes_

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=labels,
    yticklabels=labels
)

plt.xlabel("Предсказанный класс")
plt.ylabel("Истинный класс")
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

"""В датасете наблюдается умеренный дисбаланс классов (примерно 2:1:1).
Однако результаты экспериментов показывают, что модель демонстрирует
высокие значения precision, recall и F1-score для всех классов.

Макро- и взвешенные метрики практически совпадают, что свидетельствует
об отсутствии существенного влияния дисбаланса на качество модели.
В связи с этим дополнительные методы балансировки классов не применялись.
"""

nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

accuracy_score(y_test, y_pred_nb)

print(classification_report(y_test, y_pred_nb))

cm = confusion_matrix(y_test, y_pred_nb)
labels = le.classes_

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=labels,
    yticklabels=labels
)

plt.xlabel("Предсказанный класс")
plt.ylabel("Истинный класс")
plt.title("Confusion Matrix - Naive Bayes")
plt.show()

xgb = XGBClassifier(
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss',
    use_label_encoder=False,
    random_state=42
)

param_grid = {
    'n_estimators': [200, 300],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.05, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

grid = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    scoring='f1_weighted',
    cv=3,
    verbose=1,
    n_jobs=-1
)
grid.fit(X_train, y_train)

grid.best_params_

xgb_model = grid.best_estimator_
y_pred_xgb = xgb_model.predict(X_test)

accuracy_score(y_test, y_pred_xgb)

print(classification_report(y_test, y_pred_xgb))

cm = confusion_matrix(y_test, y_pred_xgb)
labels = le.classes_

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=labels,
    yticklabels=labels
)

plt.xlabel("Предсказанный класс")
plt.ylabel("Истинный класс")
plt.title("Confusion Matrix - XGBoost")
plt.show()

!pip install transformers datasets --quiet

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

X_train_texts = train_df['TEXT']
X_test_texts = test_df['TEXT']

y_train_labels = train_df['LABEL_ENC']
y_test_labels = test_df['LABEL_ENC']

tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

train_encodings = tokenizer(
    list(X_train_texts),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    list(X_test_texts),
    truncation=True,
    padding=True,
    max_length=128
)

class SMSDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels.iloc[idx])
        return item

train_dataset = SMSDataset(train_encodings, y_train_labels)
test_dataset = SMSDataset(test_encodings, y_test_labels)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased',num_labels=len(df['LABEL_ENC'].unique()))
model.to(device)

optimizer = AdamW(model.parameters(), lr=5e-5)

import time

num_epochs = 3
num_training_steps = num_epochs * len(train_loader)

lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps
)

#progress_bar = tqdm(range(num_training_steps))
start_time_distil = time.time()
train_losses = []
val_accuracies = []

for epoch in range(num_epochs):
    model.train()
    total_loss = 0

    for batch in train_loader:
        batch = {k: v.to(device) for k, v in batch.items()}

        outputs = model(**batch)
        loss = outputs.loss

        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    train_losses.append(avg_loss)

    model.eval()
    preds = []
    true_labels = []

    with torch.no_grad():
        for batch in test_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            outputs = model(**batch)

            logits = outputs.logits
            predictions = torch.argmax(logits, dim=-1)

            preds.extend(predictions.cpu().numpy())
            true_labels.extend(batch['labels'].cpu().numpy())

    acc = accuracy_score(true_labels, preds)
    val_accuracies.append(acc)

    print(f"Epoch {epoch+1}: Loss = {avg_loss:.4f}, Val Accuracy = {acc:.4f}")
end_time_distil = time.time()
total_time = end_time_distil - start_time_distil

total_time

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12,5))

ax1.plot(range(1, len(train_losses)+1), train_losses, marker='o', color='blue', linewidth=2)
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss')
ax1.set_title('Training Loss')
ax1.grid(True, alpha=0.3)
ax1.set_xticks(range(1, len(train_losses)+1))

ax2.plot(range(1, len(val_accuracies)+1), val_accuracies, marker='o', color='red', linewidth=2)
ax2.set_xlabel('Epoch')
ax2.set_ylabel('Accuracy')
ax2.set_title('Validation Accuracy')
ax2.grid(True, alpha=0.3)
ax2.set_xticks(range(1, len(val_accuracies)+1))
ax2.set_ylim(0.97, 0.99)

plt.tight_layout()
plt.show()

cm = confusion_matrix(true_labels, preds)
labels = le.classes_

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=labels,
    yticklabels=labels
)

plt.xlabel("Предсказанный класс")
plt.ylabel("Истинный класс")
plt.title("Confusion Matrix - DistilBERT")
plt.show()

tokenizer = AutoTokenizer.from_pretrained('roberta-base')

train_encodings = tokenizer(
    list(train_df['TEXT']),
    truncation=True,
    padding='max_length',
    max_length=128,
    return_tensors='pt'
)

test_encodings = tokenizer(
    list(test_df['TEXT']),
    truncation=True,
    padding='max_length',
    max_length=128,
    return_tensors='pt'
)

class SMSDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels.iloc[idx], dtype=torch.long)
        return item

train_dataset = SMSDataset(train_encodings, y_train_labels)
test_dataset = SMSDataset(test_encodings, y_test_labels)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

model = AutoModelForSequenceClassification.from_pretrained('roberta-base',num_labels=len(df['LABEL_ENC'].unique()))
model.to(device)

optimizer = AdamW(model.parameters(), lr=2e-5, eps=1e-8)
num_epochs = 3
num_training_steps = num_epochs * len(train_loader)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps
)

start_time_roberta = time.time()
train_losses = []
val_accuracies = []
for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for batch in train_loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        loss = outputs.loss
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    train_losses.append(avg_loss)

    model.eval()
    preds_roberta = []
    true_labels_roberta = []
    with torch.no_grad():
        for batch in test_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            outputs = model(**batch)
            logits = outputs.logits
            predictions = torch.argmax(logits, dim=-1)
            preds_roberta.extend(predictions.cpu().numpy())
            true_labels_roberta.extend(batch['labels'].cpu().numpy())

    acc = accuracy_score(true_labels_roberta, preds_roberta)
    val_accuracies.append(acc)
    print(f"Epoch {epoch+1}: Loss={avg_loss:.4f}, Val Accuracy={acc:.4f}")
end_time_roberta = time.time()
total_time = end_time_roberta - start_time_roberta

total_time

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12,5))

ax1.plot(range(1, len(train_losses)+1), train_losses, marker='o', color='blue', linewidth=2)
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss')
ax1.set_title('RoBERTa-base Training Loss')
ax1.grid(True, alpha=0.3)
ax1.set_xticks(range(1, len(train_losses)+1))

ax2.plot(range(1, len(val_accuracies)+1), val_accuracies, marker='o', color='red', linewidth=2)
ax2.set_xlabel('Epoch')
ax2.set_ylabel('Accuracy')
ax2.set_title('RoBERTa-base Validation Accuracy')
ax2.grid(True, alpha=0.3)
ax2.set_xticks(range(1, len(val_accuracies)+1))
ax2.set_ylim(0.97, 0.99)

plt.tight_layout()
plt.show()

cm = confusion_matrix(true_labels_roberta, preds_roberta)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=le.classes_, yticklabels=le.classes_)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix - RoBERTa-base")
plt.show()

def get_metrics(y_true, y_pred, model_name):
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average='weighted'
    )
    accuracy = accuracy_score(y_true, y_pred)

    return pd.DataFrame({
        'Model': [model_name],
        'Accuracy': [accuracy],
        'Precision (weighted)': [precision],
        'Recall (weighted)': [recall],
        'F1-score (weighted)': [f1]
    })

metrics_lr = get_metrics(y_test, y_pred_lr, 'Logistic Regression')
metrics_nb = get_metrics(y_test, y_pred_nb, 'Naive Bayes')
metrics_xgb = get_metrics(y_test, y_pred_xgb, 'XGBoost')
metrics_bert = get_metrics(true_labels, preds, 'DistilBERT')
metrics_roberta = get_metrics(true_labels_roberta, preds_roberta, 'RoBERTa-base')

metrics_df = pd.concat(
    [metrics_lr, metrics_nb, metrics_xgb, metrics_bert, metrics_roberta],
    ignore_index=True
)

metrics_df

"""DistilBERT продемонстрировал наилучший результат на SMS датасете, эффективно различает все три класса, и показывает преимущества использования предобученных трансформеров для коротких текстов."""

